

#import <Cocoa/Cocoa.h>


@interface ASCIIWindowController : NSWindowController  <NSWindowDelegate>{
  IBOutlet NSTextField* chr00;
  IBOutlet NSTextField* chr01;
  IBOutlet NSTextField* chr02;
  IBOutlet NSTextField* chr03;
  IBOutlet NSTextField* chr04;
  IBOutlet NSTextField* chr05;
  IBOutlet NSTextField* chr06;
  IBOutlet NSTextField* chr07;
  IBOutlet NSTextField* chr08;
  IBOutlet NSTextField* chr09;
  IBOutlet NSTextField* chr0a;
  IBOutlet NSTextField* chr0b;
  IBOutlet NSTextField* chr0c;
  IBOutlet NSTextField* chr0d;
  IBOutlet NSTextField* chr0e;
  IBOutlet NSTextField* chr0f;

  IBOutlet NSTextField* chr10;
  IBOutlet NSTextField* chr11;
  IBOutlet NSTextField* chr12;
  IBOutlet NSTextField* chr13;
  IBOutlet NSTextField* chr14;
  IBOutlet NSTextField* chr15;
  IBOutlet NSTextField* chr16;
  IBOutlet NSTextField* chr17;
  IBOutlet NSTextField* chr18;
  IBOutlet NSTextField* chr19;
  IBOutlet NSTextField* chr1a;
  IBOutlet NSTextField* chr1b;
  IBOutlet NSTextField* chr1c;
  IBOutlet NSTextField* chr1d;
  IBOutlet NSTextField* chr1e;
  IBOutlet NSTextField* chr1f;

  IBOutlet NSTextField* chr20;
  IBOutlet NSTextField* chr21;
  IBOutlet NSTextField* chr22;
  IBOutlet NSTextField* chr23;
  IBOutlet NSTextField* chr24;
  IBOutlet NSTextField* chr25;
  IBOutlet NSTextField* chr26;
  IBOutlet NSTextField* chr27;
  IBOutlet NSTextField* chr28;
  IBOutlet NSTextField* chr29;
  IBOutlet NSTextField* chr2a;
  IBOutlet NSTextField* chr2b;
  IBOutlet NSTextField* chr2c;
  IBOutlet NSTextField* chr2d;
  IBOutlet NSTextField* chr2e;
  IBOutlet NSTextField* chr2f;

  IBOutlet NSTextField* chr30;
  IBOutlet NSTextField* chr31;
  IBOutlet NSTextField* chr32;
  IBOutlet NSTextField* chr33;
  IBOutlet NSTextField* chr34;
  IBOutlet NSTextField* chr35;
  IBOutlet NSTextField* chr36;
  IBOutlet NSTextField* chr37;
  IBOutlet NSTextField* chr38;
  IBOutlet NSTextField* chr39;
  IBOutlet NSTextField* chr3a;
  IBOutlet NSTextField* chr3b;
  IBOutlet NSTextField* chr3c;
  IBOutlet NSTextField* chr3d;
  IBOutlet NSTextField* chr3e;
  IBOutlet NSTextField* chr3f;

  IBOutlet NSTextField* chr40;
  IBOutlet NSTextField* chr41;
  IBOutlet NSTextField* chr42;
  IBOutlet NSTextField* chr43;
  IBOutlet NSTextField* chr44;
  IBOutlet NSTextField* chr45;
  IBOutlet NSTextField* chr46;
  IBOutlet NSTextField* chr47;
  IBOutlet NSTextField* chr48;
  IBOutlet NSTextField* chr49;
  IBOutlet NSTextField* chr4a;
  IBOutlet NSTextField* chr4b;
  IBOutlet NSTextField* chr4c;
  IBOutlet NSTextField* chr4d;
  IBOutlet NSTextField* chr4e;
  IBOutlet NSTextField* chr4f;

  IBOutlet NSTextField* chr50;
  IBOutlet NSTextField* chr51;
  IBOutlet NSTextField* chr52;
  IBOutlet NSTextField* chr53;
  IBOutlet NSTextField* chr54;
  IBOutlet NSTextField* chr55;
  IBOutlet NSTextField* chr56;
  IBOutlet NSTextField* chr57;
  IBOutlet NSTextField* chr58;
  IBOutlet NSTextField* chr59;
  IBOutlet NSTextField* chr5a;
  IBOutlet NSTextField* chr5b;
  IBOutlet NSTextField* chr5c;
  IBOutlet NSTextField* chr5d;
  IBOutlet NSTextField* chr5e;
  IBOutlet NSTextField* chr5f;

  IBOutlet NSTextField* chr60;
  IBOutlet NSTextField* chr61;
  IBOutlet NSTextField* chr62;
  IBOutlet NSTextField* chr63;
  IBOutlet NSTextField* chr64;
  IBOutlet NSTextField* chr65;
  IBOutlet NSTextField* chr66;
  IBOutlet NSTextField* chr67;
  IBOutlet NSTextField* chr68;
  IBOutlet NSTextField* chr69;
  IBOutlet NSTextField* chr6a;
  IBOutlet NSTextField* chr6b;
  IBOutlet NSTextField* chr6c;
  IBOutlet NSTextField* chr6d;
  IBOutlet NSTextField* chr6e;
  IBOutlet NSTextField* chr6f;

  IBOutlet NSTextField* chr70;
  IBOutlet NSTextField* chr71;
  IBOutlet NSTextField* chr72;
  IBOutlet NSTextField* chr73;
  IBOutlet NSTextField* chr74;
  IBOutlet NSTextField* chr75;
  IBOutlet NSTextField* chr76;
  IBOutlet NSTextField* chr77;
  IBOutlet NSTextField* chr78;
  IBOutlet NSTextField* chr79;
  IBOutlet NSTextField* chr7a;
  IBOutlet NSTextField* chr7b;
  IBOutlet NSTextField* chr7c;
  IBOutlet NSTextField* chr7d;
  IBOutlet NSTextField* chr7e;
  IBOutlet NSTextField* chr7f;

  IBOutlet NSTextField* asc00;
  IBOutlet NSTextField* asc01;
  IBOutlet NSTextField* asc02;
  IBOutlet NSTextField* asc03;
  IBOutlet NSTextField* asc04;
  IBOutlet NSTextField* asc05;
  IBOutlet NSTextField* asc06;
  IBOutlet NSTextField* asc07;
  IBOutlet NSTextField* asc08;
  IBOutlet NSTextField* asc09;
  IBOutlet NSTextField* asc0a;
  IBOutlet NSTextField* asc0b;
  IBOutlet NSTextField* asc0c;
  IBOutlet NSTextField* asc0d;
  IBOutlet NSTextField* asc0e;
  IBOutlet NSTextField* asc0f;

  IBOutlet NSTextField* asc10;
  IBOutlet NSTextField* asc11;
  IBOutlet NSTextField* asc12;
  IBOutlet NSTextField* asc13;
  IBOutlet NSTextField* asc14;
  IBOutlet NSTextField* asc15;
  IBOutlet NSTextField* asc16;
  IBOutlet NSTextField* asc17;
  IBOutlet NSTextField* asc18;
  IBOutlet NSTextField* asc19;
  IBOutlet NSTextField* asc1a;
  IBOutlet NSTextField* asc1b;
  IBOutlet NSTextField* asc1c;
  IBOutlet NSTextField* asc1d;
  IBOutlet NSTextField* asc1e;
  IBOutlet NSTextField* asc1f;

  IBOutlet NSTextField* asc20;
  IBOutlet NSTextField* asc21;
  IBOutlet NSTextField* asc22;
  IBOutlet NSTextField* asc23;
  IBOutlet NSTextField* asc24;
  IBOutlet NSTextField* asc25;
  IBOutlet NSTextField* asc26;
  IBOutlet NSTextField* asc27;
  IBOutlet NSTextField* asc28;
  IBOutlet NSTextField* asc29;
  IBOutlet NSTextField* asc2a;
  IBOutlet NSTextField* asc2b;
  IBOutlet NSTextField* asc2c;
  IBOutlet NSTextField* asc2d;
  IBOutlet NSTextField* asc2e;
  IBOutlet NSTextField* asc2f;

  IBOutlet NSTextField* asc30;
  IBOutlet NSTextField* asc31;
  IBOutlet NSTextField* asc32;
  IBOutlet NSTextField* asc33;
  IBOutlet NSTextField* asc34;
  IBOutlet NSTextField* asc35;
  IBOutlet NSTextField* asc36;
  IBOutlet NSTextField* asc37;
  IBOutlet NSTextField* asc38;
  IBOutlet NSTextField* asc39;
  IBOutlet NSTextField* asc3a;
  IBOutlet NSTextField* asc3b;
  IBOutlet NSTextField* asc3c;
  IBOutlet NSTextField* asc3d;
  IBOutlet NSTextField* asc3e;
  IBOutlet NSTextField* asc3f;

  IBOutlet NSTextField* asc40;
  IBOutlet NSTextField* asc41;
  IBOutlet NSTextField* asc42;
  IBOutlet NSTextField* asc43;
  IBOutlet NSTextField* asc44;
  IBOutlet NSTextField* asc45;
  IBOutlet NSTextField* asc46;
  IBOutlet NSTextField* asc47;
  IBOutlet NSTextField* asc48;
  IBOutlet NSTextField* asc49;
  IBOutlet NSTextField* asc4a;
  IBOutlet NSTextField* asc4b;
  IBOutlet NSTextField* asc4c;
  IBOutlet NSTextField* asc4d;
  IBOutlet NSTextField* asc4e;
  IBOutlet NSTextField* asc4f;
  
  IBOutlet NSTextField* asc50;
  IBOutlet NSTextField* asc51;
  IBOutlet NSTextField* asc52;
  IBOutlet NSTextField* asc53;
  IBOutlet NSTextField* asc54;
  IBOutlet NSTextField* asc55;
  IBOutlet NSTextField* asc56;
  IBOutlet NSTextField* asc57;
  IBOutlet NSTextField* asc58;
  IBOutlet NSTextField* asc59;
  IBOutlet NSTextField* asc5a;
  IBOutlet NSTextField* asc5b;
  IBOutlet NSTextField* asc5c;
  IBOutlet NSTextField* asc5d;
  IBOutlet NSTextField* asc5e;
  IBOutlet NSTextField* asc5f;

  IBOutlet NSTextField* asc60;
  IBOutlet NSTextField* asc61;
  IBOutlet NSTextField* asc62;
  IBOutlet NSTextField* asc63;
  IBOutlet NSTextField* asc64;
  IBOutlet NSTextField* asc65;
  IBOutlet NSTextField* asc66;
  IBOutlet NSTextField* asc67;
  IBOutlet NSTextField* asc68;
  IBOutlet NSTextField* asc69;
  IBOutlet NSTextField* asc6a;
  IBOutlet NSTextField* asc6b;
  IBOutlet NSTextField* asc6c;
  IBOutlet NSTextField* asc6d;
  IBOutlet NSTextField* asc6e;
  IBOutlet NSTextField* asc6f;

  IBOutlet NSTextField* asc70;
  IBOutlet NSTextField* asc71;
  IBOutlet NSTextField* asc72;
  IBOutlet NSTextField* asc73;
  IBOutlet NSTextField* asc74;
  IBOutlet NSTextField* asc75;
  IBOutlet NSTextField* asc76;
  IBOutlet NSTextField* asc77;
  IBOutlet NSTextField* asc78;
  IBOutlet NSTextField* asc79;
  IBOutlet NSTextField* asc7a;
  IBOutlet NSTextField* asc7b;
  IBOutlet NSTextField* asc7c;
  IBOutlet NSTextField* asc7d;
  IBOutlet NSTextField* asc7e;
  IBOutlet NSTextField* asc7f;

  IBOutlet NSSegmentedControl* numbercontrol;
  IBOutlet NSSegmentedControl* codecontrol;
  IBOutlet NSTextField* comment1;
  IBOutlet NSTextField* comment2;
  int currenthighlight;
}

-(void)awakeFromNib;
-(void)showDialog;
-(void)update;
-(IBAction)segmentControlChange:(NSControl*)sender;
- (void)mouseEntered:(NSEvent *)theEvent;
- (void)mouseExited:(NSEvent *)theEvent;

@end
